### ISSUE TITLE
Error while trying to get ping stats

### ISSUE THREAD

**Issue by Swarkin** [Owen-Cochell/mctools#15]
![image](https://github.com/Owen-Cochell/mctools/assets/102416174/29a238ce-3ace-41cb-a1bb-42e63ac9b22f)

Any idea why?

**Comment by Owen-Cochell** [comment]
Hello! Thank you for reporting this.

First off, are you certain that the resource you are pointing mctools at is a minecraft server? This error may occur if there is a service other than minecraft running at the provided IP and port, as mctools is trying to work with information that is not structured as it expects. A good way to test this is to add the server to your server list in the minecraft client and checking if the ping is successful. Be sure to double check!

If this is a valid minecraft server, could you send me some information on it? The version, server type (vanilla, papermc, bukkit, etc.), and any plugins installed would be helpful pieces of info if you know them. Ideally, if you own this server, you could send me the address so I can do some testing myself to see what is going on. You can email the address to me if you don't want it to be sent publicly over GitHub. The server you are pinging may have some interesting features that can cause this error, and I would like to fix mctools so it can deal with similar scenarios in the future.

Thanks!

**Comment by Swarkin** [comment]
Hmm it might be because the server is using the ngrok service, so if it loses connection, restarts or anything really, the IP changes. But because of the fact that it is using ngrok that same IP might get assigned to another person's application and it breaks because of this. Let me check if that is actually what's happening

**Comment by Swarkin** [comment]
Okay seems like this was the issue 😅
Sorry for that
